# Generated by Django 3.2 on 2021-10-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=50)),
                ('creditstatus', models.CharField(max_length=50)),
                ('others', models.TextField()),
            ],
        ),
    ]
